[mypy]
# Imports
follow_untyped_imports = True

# Dynamic typing
# ! disallow_any_expr = True
# ! disallow_any_decorated = True
# ! disallow_any_explicit = True
# ! disallow_any_generics = True
# ! disallow_any_unimported = True
disallow_subclassing_any = True

# Untyped definitions and calls
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
# ! disallow_untyped_calls = True

# None and Optional
no_implicit_optional = True
strict_optional = True

# Warnings
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
warn_return_any = True
warn_unreachable = True
report_deprecated_as_note = True
warn_unused_configs = True

# Strictness flags
allow_untyped_globals = False
allow_redefinition = False
strict_equality = True
